config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: 'users#index'

    # Users
    resources :users
    put 'block_user', to: 'users#block_user'
    put 'activate_user', to: 'users#activate_user'

    # Languages
    resources :languages
    post 'create_from_select', to: 'languages#create_from_select'
    put 'change_language_status', to: 'languages#change_language_status'

    # Categories
    resources :categories
    post 'create_sub_category', to: 'categories#create_sub_category'
    post 'create_team', to: 'categories#create_team'
    put 'edit_team', to: 'categories#edit_team'
    delete 'destroy_team', to: 'categories#destroy_team'

    # Team
    resources :teams

    # Articles
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  root to: 'home#home'
end

app/models/article.rb
class Article < ApplicationRecord
  include Commentable

  has_one_attached :photo
  has_many :comments, as: :commentable, dependent: :destroy
  has_rich_text :content

  belongs_to :location
  belongs_to :category, inverse_of: :articles

  validates :headline, presence: true, length: { maximum: 100 }
  validates :alt_text, length: { maximum: 100 }
  validates :caption, presence: true, length: { maximum: 100 }
  validates :location_id, presence: true
  validates :category_id, presence: true

  scope :published, -> { where(is_published: true) }
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < BaseController
    before_action :parent_info, except: [:destroy, :create]
    before_action :find_article!, except: [:new, :create, :index]

    def index
      @articles = Article.where(category_id: params[:category]).page(params[:page])
      @category = Category.find(params[:category])
    end

    def show; end

    def new
      @article = Article.new
      @category = Category.find(params[:category])
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to admin_articles_path('category' => @article.category_id), notice: 'Article created.'
      else
        redirect_to admin_articles_path('category' => @article.category_id), alert: 'Unable to create article.'
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      if @article.update(article_params)
        redirect_to admin_articles_path('category' => @article.category_id), notice: 'Article updated.'
      else
        redirect_to admin_articles_path('category' => @article.category_id), alert: 'Unable to update articles.'
      end
    end

    def destroy
      if @article.destroy
        redirect_to admin_user_path, notice: 'User updated.'
      else
        redirect_to admin_user_path, alert: 'Unable to update users.'
      end
    end

    private

    def article_params
      params.require(:article).permit(:photo, :headline, :alt_text, :caption, :content,
                                      :location_id, :category_id, :is_published)
    end

    def find_article!
      @article = Article.find(params[:id])
    end

    def parent_info
      @locations = Location.all
      @sub_categories = Category.all
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout 'application'

  def index
    @articles = Article.published.where(category_id: params[:category_id]).page(params[:page])
  end

  def show
    @article = Article.published.find(params[:id])
  end
end

app/views/articles/_title_new.html.erb
<div class="row" style="border: 2px solid black">
  <div class="titleName col-10">Languages</div>
  <div class="col-2">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newModal">
      + New Language
    </button>
    <div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="newModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addModalLabel">Add language</h5>
          </div>
          <%= form_tag admin_create_from_select_path, :method => :post do %>
            <div class="modal-body">
              <%= select_tag "Select Languages",
                             raw("<option value='English/en'>English</option>
                                  <option value='French/fr'>French</option>
                                  <option value='Spanish/es'>Spanish</option>
                                  <option value='German/gr'>German</option>"),
                             multiple: true,
                             class: 'form-select',
                             id: 'languages-select'
              %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
              <%= submit_tag 'Add', :class=>'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<%= render :partial => 'common/article', collection:  @articles || [] %>
<%= paginate @articles %>

app/views/articles/show.html.erb
<div class="article-box row" style="margin-bottom: 50px">
  <div class="photo-box col-auto">
    <%= render_article_photo(@article) %>
  </div>
  <div class="article_info_box col">
    <h1><%= @article.headline %></h1><br/>
    <a><%= @article.content %></a>
  </div>
</div>
<div class="comment-box">
  <%= render :partial => 'common/comments/comments', locals: { commentable: @article } %><br>
  <% if current_user.nil? %>
    <p>Log in to write commentary</p>
  <% else %>
    <%= form_for [@article, Comment.new], url: article_comments_path(@article), html: { method: :post} do |f| %>
      <div class="field">
        <%= f.hidden_field :user_id, value: current_user.id  %>
      </div>
      <div class="form-group">
        <%= f.text_area :body, class: "form-control", placeholder: "Add a comment" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>