config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: 'users#index'

    # Users
    resources :users
    put 'block_user', to: 'users#block_user'
    put 'activate_user', to: 'users#activate_user'

    # Languages
    resources :languages
    post 'create_from_select', to: 'languages#create_from_select'
    put 'change_language_status', to: 'languages#change_language_status'

    # Categories
    resources :categories
    post 'create_sub_category', to: 'categories#create_sub_category'
    post 'create_team', to: 'categories#create_team'
    put 'edit_team', to: 'categories#edit_team'
    delete 'destroy_team', to: 'categories#destroy_team'

    # Team
    resources :teams

    # Articles
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  root to: 'home#home'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  belongs_to :parent_category, class_name: 'Category', inverse_of: :sub_categories, optional: true
  has_many :sub_categories, class_name: 'Category', foreign_key: 'parent_category_id',
                            inverse_of: :parent_category, dependent: :destroy
  has_many :teams, class_name: 'Team', foreign_key: 'categories_id', inverse_of: :categories, dependent: :destroy
  has_many :articles, inverse_of: :category, dependent: :destroy

  scope :primary, -> { where(parent_category_id: nil) }
  scope :sub_categories, -> { where.not(parent_category: nil) }

  validate :category_nesting

  def sub_category?
    parent_category_id.present?
  end

  def primary_category?
    parent_category_id.nil?
  end

  private

  def category_nesting
    errors.add(:parent_category_id, 'You can not use this category as parent.') if parent_category&.sub_category?
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController
    def index
      @primary_categories = Category.primary.page(params[:page])

      return unless @primary_categories.any?

      @selected_category_id = params[:parent_category_id] || @primary_categories.first.id

      load_sub_categories_and_teams
    end

    def load_sub_categories_and_teams
      @sub_categories = Category.where(parent_category_id: @selected_category_id.to_i)

      return unless @sub_categories.any?

      @selected_sub_category_id = params[:sub_categories_id] || @sub_categories.first.id
      @teams = Team.select { |team| team.categories_id == @selected_sub_category_id.to_i }
      @teams = Team.where(categories_id: @selected_sub_category_id.to_i)
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: 'Your category was successfully added.'
      else
        redirect_to admin_categories_path, alert: "Your category wasn't added."
      end
      @category.save
    end

    def create_sub_category
      @sub_category = Category.new(sub_category_params)

      return unless @sub_category.save

      redirect_to admin_categories_path('parent_category_id' => @sub_category.parent_category_id,
                                        'sub_categories_id' => @sub_category.id)
    end

    def create_team
      @team = Team.new(sub_category_team_params)
      @team.save

      sub_category = Category.find(@team.categories_id)
      redirect_to admin_categories_path('parent_category_id' => sub_category.parent_category_id,
                                        'sub_categories_id' => sub_category.id)
    end

    def edit_team
      @team = Team.find(params[:id])
    end

    def update_team
      @team = Team.find(params[:id])
      if @team.update(teams_params)
        redirect_to admin_categories_path, notice: 'Team updated.'
      else
        redirect_to admin_categories_path, alert: 'Unable to update team.'
      end
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        redirect_to admin_categories_path, notice: 'User updated.'
      else
        redirect_to admin_categories_path, alert: 'Unable to update users.'
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      if @category.parent_category_id.nil?
        redirect_to admin_categories_path
      else
        redirect_to admin_categories_path('parent_category_id' => @category.parent_category_id)
      end
    end

    def destroy_team
      @team = Team.find(params[:id])
      @team.destroy

      sub_category = Category.find(@team.categories_id)
      redirect_to admin_categories_path('parent_category_id' => sub_category.parent_category_id,
                                        'sub_categories_id' => sub_category.id)
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end

    def sub_category_params
      params.require(:category).permit(:name, :parent_category_id)
    end

    def sub_category_team_params
      params.require(:teams).permit(:name, :location, :categories_id, :category)
    end
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td class="w-50"><%= link_to category.name, admin_categories_path(:parent_category_id => category, :page => params[:page]) %></td>
  <td><%= link_to "Edit", edit_admin_category_path(category) %>
    <%= link_to 'Delete', admin_category_path(category), :data => { :confirm => "Are you sure?"},
                :class => 'button-xs', :method => :delete %></td>
</tr>

app/views/admin/categories/_new.html.erb
<div class="modal fade" id="newCategoryModal" tabindex="-1" role="dialog" aria-labelledby="newCategoryModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newCategoryModalLabel">Add Category</h5>
      </div>
      <%= form_for Category, as: :category, url: admin_categories_path, html: { method: :post } do |f| %>
        <div class="modal-body">
          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
          <%= submit_tag 'Add', :class=>'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_new_team.html.erb
<div class="modal fade" id="newTeamModal" tabindex="-1" role="dialog" aria-labelledby="newTeamModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newTeamModalLabel">Add Team</h5>
      </div>
      <%= form_for Team, as: :teams, url: admin_create_team_path, html: { method: :post } do |f| %>
        <div class="modal-body">
          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true %>
          </div><br />
          <div class="field">
            <%= f.label :location %><br />
            <input type="text" value="Teams" name="teams[location]" id="teams_location">
          </div><br />
          <%= f.hidden_field :categories_id, value: @selected_sub_category_id  %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
          <%= submit_tag 'Add', :class=>'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_sub_new.html.erb
<div class="modal fade" id="newSubCategoryModal" tabindex="-1" role="dialog" aria-labelledby="newSubCategoryModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSubCategoryModalLabel">Add Sub Category</h5>
      </div>
      <%= form_for Category, as: :category,
                   url: admin_create_sub_category_path,
                   html: { method: :post } do |f| %>
        <div class="modal-body">
          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true%>
          </div><br />
          <%= f.hidden_field :parent_category_id, value: @selected_category_id  %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
          <%= submit_tag 'Add', :class=>'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<div class="row h-auto">
  <%= link_to 'Back', admin_categories_path %>
</div>
<div class="row h-75">
  <%= form_for Category, as: :category, url: admin_category_path, html: { method: :put } do |f| %>
    <%= f.label 'Name' %><br>
    <%= f.text_field :name, :value => @category.name %><br>

    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/admin/categories/edit_team.html.erb
<div class="row h-auto">
  <%= link_to 'Back', admin_categories_path %>
</div>
<div class="row h-75">
  <%= form_for Team, as: :teams, url: admin_edit_team_path(@team), html: { method: :put } do |f| %>
    <%= f.label 'Name' %><br>
    <%= f.text_field :name, :value => @team.name %><br>

    <%= f.label 'Location' %><br>
    <%= f.text_field :location, :value => @team.location %><br>

    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<%= javascript_pack_tag 'category' %>
<div class="row align-items-center">
  <div class="table_block col-3 m-5">
    <div class="modal-block">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newCategoryModal">
        +Add category
      </button>
      <%= render :partial => 'admin/categories/new' %>
    </div>
    <table class="table" id="categoriesTable">
      <thead>
        <tr>
          <td>Name</td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        <%= render @primary_categories || [] %>
      </tbody>
    </table>
    <%= paginate @primary_categories %>
  </div>
  <div class="table_block col-3">
    <div class="modal-block">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newSubCategoryModal">
        +Add sub category
      </button>
      <%= render :partial => 'admin/categories/sub_new' %>
    </div>
    <table class="table" id="subCategoriesTable">
      <thead>
      <tr>
        <td>Name</td>
        <td></td>
      </tr>
      </thead>
      <tbody>
      <% (@sub_categories || []).each do |sub_category| %>
        <tr>
          <td class="w-50"><%= link_to sub_category.name,
                                       admin_categories_path(
                                         :parent_category_id => @selected_category_id,
                                         :sub_categories_id => sub_category
                                       ) %></td>
          <td><%= link_to "Edit", edit_admin_category_path(sub_category) %>
              <%= link_to 'Delete', admin_category_path(sub_category), :data => { :confirm => "Are you sure?"},
                          :class => 'button-xs', :method => :delete %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div class="table_block col-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newTeamModal">
      +Add team
    </button>
    <%= render :partial => 'admin/categories/new_team' %>
    <table class="table" id="teamTable">
      <thead>
      <tr>
        <td>Name</td>
        <td></td>
      </tr>
      </thead>
      <tbody>
      <% (@teams || []).each do |team| %>
        <tr>
          <td class="w-50"><%= team.name %></td>
          <td><%= link_to 'Edit', edit_admin_team_path(team), :class => 'button-xs' %>
              <%= link_to 'Delete', admin_destroy_team_path(:id => team), :data => { :confirm => "Are you sure?"},
                          :class => 'button-xs', :method => :delete %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>