config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: 'users#index'

    # Users
    resources :users
    put 'block_user', to: 'users#block_user'
    put 'activate_user', to: 'users#activate_user'

    # Languages
    resources :languages
    post 'create_from_select', to: 'languages#create_from_select'
    put 'change_language_status', to: 'languages#change_language_status'

    # Categories
    resources :categories
    post 'create_sub_category', to: 'categories#create_sub_category'
    post 'create_team', to: 'categories#create_team'
    put 'edit_team', to: 'categories#edit_team'
    delete 'destroy_team', to: 'categories#destroy_team'

    # Team
    resources :teams

    # Articles
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  root to: 'home#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar

  enum status: { active: 'active', blocked: 'blocked' }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :avatar, presence: false

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :authorize_user!, except: :index

    def index
      params[:is_admin] = false if params[:is_admin].nil?
      @search = User.ransack(params[:q])
      @users = policy_scope(@search.result.where(is_admin: params[:is_admin])).page(params[:page])
    end

    def show
      render json: { html: User.find(params[:id]) }
    end

    def update
      if @user.update(secure_params)
        redirect_to admin_user_path, notice: 'User updated.'
      else
        redirect_to admin_user_path, alert: 'Unable to update users.'
      end
    end

    def destroy
      @user.destroy
      return unless user.destroyed?

      ApplicationMailer.with(user: user).destroy_user_notify.deliver_later
      redirect_to admin_root_path
    end

    def block_user
      @user.assign_attributes({ status: 'blocked' })

      service = UserService::Block.new

      if service.call user: @user
        redirect_to admin_root_path
        service.send_status_mail user: @user, status: 'blocked'
      else
        flash[:error] = service.errors.first
      end
    end

    def activate_user
      @user.assign_attributes({ status: 'active' })

      service = UserService::Activate.new

      if service.call user: @user
        service.send_status_mail user: @user, status: 'activated'
        redirect_to admin_root_path
      else
        flash[:error] = service.errors.first
      end
    end

    private

    def secure_params
      params.require(:user).permit(:first_name, :last_name, :status, :avatar)
    end

    def authorize_user!
      @user = User.find(params[:id])
      authorize @user
    end
  end
end

app/views/admin/users/_admin.html.erb
<tr>
  <td><%= user.full_name %></td>
  <td><%= user.status %></td>
  <td>
    <%= link_to 'Remove from Admin', admin_user_path(admin),
                :data => { :confirm => "Are you sure?" },
                :class => 'button-xs' unless user == current_user || !admin.is_admin? %>
  </td>
</tr>

app/views/admin/users/_title_new.html.erb
<div class="row" style="border: 2px solid black">
  <div class="titleName col-10">Users</div>
</div>

app/views/admin/users/_user.html.erb
<tr id="<%= user.id %>" class="clickable-row">
  <td><%= user.full_name %></td>
  <td><%= user.status %></td>
  <td>
    <% if locals[:is_admin] == 'true' %>
      <%= link_to 'Remove from Admin', admin_user_path(user),
                  :data => { :confirm => "Are you sure?" },
                  :class => 'button-xs' unless user == current_user %>
    <% else %>
      <% if user.status == 'active' %>
        <%= link_to 'Block', admin_block_user_path(:id => user), :data => { :confirm => "Are you sure?"},
                    :class => 'button-xs', :method => :put unless user == current_user %>
      <% else %>
          <%= link_to 'Activate', admin_activate_user_path(:id => user), :data => { :confirm => "Are you sure?" },
                      :class => 'button-xs', :method => :put unless user == current_user %>
      <% end %>
    <% end %>
    <%= link_to 'Delete', admin_user_path(user), :data => { :confirm => "Are you sure?" },
                :method => :delete, :class => 'button-xs' unless user == current_user %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<%= javascript_pack_tag 'admin_user' %>
<%#= stylesheet_link_tag '' %>
<div class="table_block col-8 m-5">
    <div class="row">
      <div class="col-1">
        <%= link_to "Users", admin_users_path(:is_admin => false) %>
      </div>
      <div class="col-1">
        <%= link_to "Admins", admin_users_path(:is_admin => true) %>
      </div>
      <div class="col-3">
        <%= search_form_for @search, url: admin_users_path(is_admin: params[:is_admin]) do |f| %>
          <%= f.search_field :first_name_or_last_name_cont %>
        <% end %>
      </div>
      <div class="col-5"></div>
      <div class="col">
        <%= sort_link(@search, :status, 'Sort by status') %>
      </div>
    </div>
    <div class="tab-pane fade show active" id="users" role="tabpanel" aria-labelledby="users-tab">
      <table id='users_table' class="table table-striped">
        <tr>
          <td>Name</td>
          <td>Status</td>
          <td>Actions</td>
        </tr>
        <%= render @users, :locals => {:is_admin => params[:is_admin]} %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
  <div class="col">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">General info</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Teams</button>
      </li>
    </ul>
    <div class="tab-content border" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <div class="row p-4">
          <div class="col align-self-start"></div>
          <div class="col align-self-center"><%= image_tag "avatar.jpg", class: "rounded-circle", style: "width: 120px" %></div>
          <div class="col align-self-end"></div>
        </div>
        <div class="row p-2">
          <div class="col ms-3">Registered</div>
          <div class="col text-end"><a class="m-3" id='user_registered'></a></div>
        </div>
        <div class="row p-2">
          <div class="col ms-3">Passed Surveys</div>
          <div class="col text-end"><a class="m-3" id='user_surveys'>-</a></div>
        </div>
        <div class="row p-2">
          <div class="col ms-3">Teams</div>
          <div class="col text-end"><a class="m-3" id='user_teams'>-</a></div>
        </div>
      </div>
      <div class="tab-pane border fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

      </div>
    </div>
  </div>