config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: 'users#index'

    # Users
    resources :users
    put 'block_user', to: 'users#block_user'
    put 'activate_user', to: 'users#activate_user'

    # Languages
    resources :languages
    post 'create_from_select', to: 'languages#create_from_select'
    put 'change_language_status', to: 'languages#change_language_status'

    # Categories
    resources :categories
    post 'create_sub_category', to: 'categories#create_sub_category'
    post 'create_team', to: 'categories#create_team'
    put 'edit_team', to: 'categories#edit_team'
    delete 'destroy_team', to: 'categories#destroy_team'

    # Team
    resources :teams

    # Articles
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  root to: 'home#home'
end

app/views/common/_article.html.erb
<div class="article-box row" style="margin-bottom: 50px">
  <div class="photo-box col-auto">
    <%= render_article_photo(article) %>
  </div>
  <div class="article_info_box col">
    <% if base_class_name == 'Admin::BaseController' %>
      <h1><%= link_to article.headline, edit_admin_article_path(:id => article.id) %></h1>
    <% elsif base_class_name == 'ApplicationController' %>
      <h1><%= link_to article.headline, article_path(:id => article.id) %></h1>
    <% end %>
    <a><%= article.content %></a>
    <!--  <a><%#= article.category.name %> / <%#= category.location.name %></a>-->
  </div>
</div>

app/views/common/_header.html.erb
<div class="navbar navbar-expand-lg" style="height: 100px">
  <div class="navbar-brand h-100 w-25 text-center" style="background-color: #d72130; padding-top: 25px">
    <h3 style="color:white;">Sports Hub</h3>
  </div>
  <div class="navbar-collapse" style="background-color: white;">
    <%= render :partial => 'common/search' if current_layout == 'application' %>
  </div>
  <div class="nav mr-auto border h-100">
    <% if user_signed_in? %>
      <% if current_user.is_admin? %>
        <div class="navbar-collapse align-items-center">
          <%= link_to "Switch", (controller.is_a?(Admin::BaseController)) ? root_path : admin_root_path %>
        </div>
      <% end %>
      <%= render :partial => 'common/profile_item' %>
    <% else %>
      <div class="navbar-collapse align-items-center"><%= link_to 'Log In', new_user_session_path %></div>
      <div class="navbar-collapse align-items-center"><%= link_to 'Sign up', new_user_registration_path %></div>
    <% end %>
    <select onchange="window.location=this.value">
      <% @active_locales.each do |l| %>
        <% if l.is_active %>
          <option value="?locale=<%= l.locale_name %>" <%= current_locale == l.locale_name ? 'selected' : '' %>>
            <%= l.locale_name %>
          </option>
        <% end %>
      <% end %>
    </select>
  </div>
</div>

app/views/common/_profile_item.html.erb
<div class="collapse navbar-collapse" id="navbar-list">
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <td>
        <%= render_user_avatar %>
        </td>
        <%= current_user[:first_name] + ' ' + current_user[:last_name] %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to 'Dashboard', edit_user_registration_path, :method => :get, class: "nav-link"%>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "nav-link"%>
      </div>
    </li>
  </ul>
</div>

app/views/common/_search.html.erb
<%= t(:search_by) %>